### PR TITLE
Added Selenium exception InvalidElementStateException

### PR DESCRIPTION
**Pull request by jyejare**
Added the `InvalidElementStateException` exception to the list of exceptions to be imported from widgedastic!

### CODE REVIEW

**Comment by quarckster** [comment]
@jyejare please fix linting errors.

**Comment by jyejare** [comment]
@quarckster Not sure why the PR is closed. Is it accidental close ?

**Comment by quarckster** [comment]
I thought you don't need it anymore because [the](https://github.com/SatelliteQE/robottelo/pull/9177) was closed. I reopened it.

**Comment by jyejare** [comment]
@quarckster Yeah ! From project perspective this is not really needed but might help some other teams. Its not a big contribution though :)

**Comment by quarckster** [comment]
@jyejare could you please fix your PR then to pass the tests?

**Pull request closed without merging**
