### PR TITLE
[RFR]Send Enter after filling value in some cases

### PR DESCRIPTION
**Pull request by sshveta**
In V2V text input , enter has to be sent after filling data .
Added a parameter "send_enter" , by default False.

### CODE REVIEW

**Comment by izapolsk** [comment]
@sshveta, I'd rather you used after_fill in such case. could you share any details where you need this feature ?

**Comment by sshveta** [comment]
> @sshveta, I'd rather you used after_fill in such case. could you share any details where you need this feature ?

Hi @izapolsk : Here is the usage of enter 
https://github.com/ManageIQ/integration_tests/blob/master/cfme/v2v/migrations.py#L538.
Initially I wrote a widget in widgetastic 
https://github.com/ManageIQ/integration_tests/pull/8399/files#diff-264354a78406ae4ca6d836bd7388d376R5167

But then as per Mike's suggestion made this core enhancement.

**Comment by izapolsk** [comment]
@sshveta, so, I'd just use after_fill instead if @mshriver doesn't mind.

**Comment by sshveta** [comment]
Closing

**Pull request closed without merging**
