### PR TITLE
Fix the project name for uploading to PyPI

### PR DESCRIPTION
**Pull request by rsnyman**

### CODE REVIEW

**Review by RonnyPfannschmidt — COMMENTED** [review]
This seems like a break

**Comment by rsnyman** [comment]
@RonnyPfannschmidt I'm trying to fix the uploading to PyPI. The error message is the following:

```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid API Token: project-scoped token is not valid for project:      
         'widgetastic', project-scoped token is not valid for project:          
         'widgetastic'                       
```

**Comment by rsnyman** [comment]
The project name on PyPI is "widgetastic.core" => https://pypi.org/project/widgetastic.core/

**Comment by RonnyPfannschmidt** [comment]
I just took a deeper look, #222 had the name change by mistake

**Comment by rsnyman** [comment]
Yes, the value in setup.cfg was "widgetastic.core"

https://github.com/RedHatQE/widgetastic.core/commit/93b572f4a027ea75259560e96f2509df036d4bfc#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L2

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by rsnyman** [comment]
Thanks @RonnyPfannschmidt !

**Pull request merged**
